//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenaris.View.Exit.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tenaris.View.Exit.Language.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Pipes.
        /// </summary>
        public static string AvailableItems {
            get {
                return ResourceManager.GetString("AvailableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Bundle.
        /// </summary>
        public static string btnDelBundle {
            get {
                return ResourceManager.GetString("btnDelBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Pipe.
        /// </summary>
        public static string btnDelPipe {
            get {
                return ResourceManager.GetString("btnDelPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Bundle.
        /// </summary>
        public static string btnInsBundle {
            get {
                return ResourceManager.GetString("btnInsBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Pipe.
        /// </summary>
        public static string btnInsPipe {
            get {
                return ResourceManager.GetString("btnInsPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Pipe.
        /// </summary>
        public static string btnMovePipe {
            get {
                return ResourceManager.GetString("btnMovePipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Bundle.
        /// </summary>
        public static string btnSendBundle {
            get {
                return ResourceManager.GetString("btnSendBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Print.
        /// </summary>
        public static string btnTagPrint {
            get {
                return ResourceManager.GetString("btnTagPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bundle.
        /// </summary>
        public static string btnUpdBundle {
            get {
                return ResourceManager.GetString("btnUpdBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle Detail.
        /// </summary>
        public static string BundleDetail {
            get {
                return ResourceManager.GetString("BundleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle Id.
        /// </summary>
        public static string BundleId {
            get {
                return ResourceManager.GetString("BundleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles.
        /// </summary>
        public static string Bundles {
            get {
                return ResourceManager.GetString("Bundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rework Bundles.
        /// </summary>
        public static string BundlesRework {
            get {
                return ResourceManager.GetString("BundlesRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle Status :.
        /// </summary>
        public static string BundleStatus {
            get {
                return ResourceManager.GetString("BundleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cradles.
        /// </summary>
        public static string Cradles {
            get {
                return ResourceManager.GetString("Cradles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FilterDate {
            get {
                return ResourceManager.GetString("FilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FilterFromDate {
            get {
                return ResourceManager.GetString("FilterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string FilterOrder {
            get {
                return ResourceManager.GetString("FilterOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno.
        /// </summary>
        public static string FilterShift {
            get {
                return ResourceManager.GetString("FilterShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string FilterToDate {
            get {
                return ResourceManager.GetString("FilterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Number.
        /// </summary>
        public static string HeatNumber {
            get {
                return ResourceManager.GetString("HeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string LblLoaded {
            get {
                return ResourceManager.GetString("LblLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string LblMaximum {
            get {
                return ResourceManager.GetString("LblMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Pieces.
        /// </summary>
        public static string LoadedPieces {
            get {
                return ResourceManager.GetString("LoadedPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Assigned Pieces.
        /// </summary>
        public static string NotAssignedPieces {
            get {
                return ResourceManager.GetString("NotAssignedPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Pieces.
        /// </summary>
        public static string PendingPieces {
            get {
                return ResourceManager.GetString("PendingPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces.
        /// </summary>
        public static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe Status :.
        /// </summary>
        public static string PipeStatus {
            get {
                return ResourceManager.GetString("PipeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe Type.
        /// </summary>
        public static string PipeType {
            get {
                return ResourceManager.GetString("PipeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmed Pieces.
        /// </summary>
        public static string ProgrammedPieces {
            get {
                return ResourceManager.GetString("ProgrammedPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State (Dialog example).
        /// </summary>
        public static string StateDialogTitle {
            get {
                return ResourceManager.GetString("StateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Sent Error.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string StatusGood {
            get {
                return ResourceManager.GetString("StatusGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Process.
        /// </summary>
        public static string StatusInProcess {
            get {
                return ResourceManager.GetString("StatusInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Sent Ok.
        /// </summary>
        public static string StatusOk {
            get {
                return ResourceManager.GetString("StatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Sent Pending.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string StatusRejected {
            get {
                return ResourceManager.GetString("StatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rework.
        /// </summary>
        public static string StatusRework {
            get {
                return ResourceManager.GetString("StatusRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap.
        /// </summary>
        public static string StatusScrap {
            get {
                return ResourceManager.GetString("StatusScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warned.
        /// </summary>
        public static string StatusWarned {
            get {
                return ResourceManager.GetString("StatusWarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Code.
        /// </summary>
        public static string SteelCode {
            get {
                return ResourceManager.GetString("SteelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteelGrade.
        /// </summary>
        public static string SteelGrade {
            get {
                return ResourceManager.GetString("SteelGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traceability.
        /// </summary>
        public static string Traceability {
            get {
                return ResourceManager.GetString("Traceability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User :.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ViewName1 {
            get {
                return ResourceManager.GetString("ViewName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string ViewName2 {
            get {
                return ResourceManager.GetString("ViewName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic.
        /// </summary>
        public static string ViewName3 {
            get {
                return ResourceManager.GetString("ViewName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
