//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Tamsa.Manager.Exit.SendIT
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "MANUGPVSOAP11Binding", Namespace = "http://namespace.softwareag.com/entirex/xml/mapping")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(string[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(decimal[]))]
    public partial class PIPFinishingExitApplication : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback PIN135W1OperationCompleted;

        private System.Threading.SendOrPostCallback PIN149FOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public PIPFinishingExitApplication(string url)
        {
            this.Url = url;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event PIN135W1CompletedEventHandler PIN135W1Completed;

        /// <remarks/>
        public event PIN149FCompletedEventHandler PIN149FCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PIN135W1", RequestNamespace = "urn:com-softwareag-entirex-rpc:MANUGPV", ResponseNamespace = "urn:com-softwareag-entirex-rpc:MANUGPV", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("COUPLINGCONSUMPTIONREPORT", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN135W1ResponseCOUPLINGCONSUMPTIONREPORT PIN135W1([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] PIN135W1COUPLINGCONSUMPTIONREPORT COUPLINGCONSUMPTIONREPORT, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] PIN135W1PIECEWITHERROR PIECEWITHERROR, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] PIN135W1STANDARERROREA STANDARERROREA, [System.Xml.Serialization.XmlElementAttribute("PIECEWITHERROR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] out PIN135W1ResponsePIECEWITHERROR PIECEWITHERROR1, [System.Xml.Serialization.XmlElementAttribute("STANDARERROREA", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] out PIN135W1ResponseSTANDARERROREA STANDARERROREA1)
        {
            object[] results = this.Invoke("PIN135W1", new object[] {
                        COUPLINGCONSUMPTIONREPORT,
                        PIECEWITHERROR,
                        STANDARERROREA});
            PIECEWITHERROR1 = ((PIN135W1ResponsePIECEWITHERROR)(results[1]));
            STANDARERROREA1 = ((PIN135W1ResponseSTANDARERROREA)(results[2]));
            return ((PIN135W1ResponseCOUPLINGCONSUMPTIONREPORT)(results[0]));
        }

        /// <remarks/>
        public void PIN135W1Async(PIN135W1COUPLINGCONSUMPTIONREPORT COUPLINGCONSUMPTIONREPORT, PIN135W1PIECEWITHERROR PIECEWITHERROR, PIN135W1STANDARERROREA STANDARERROREA)
        {
            this.PIN135W1Async(COUPLINGCONSUMPTIONREPORT, PIECEWITHERROR, STANDARERROREA, null);
        }

        /// <remarks/>
        public void PIN135W1Async(PIN135W1COUPLINGCONSUMPTIONREPORT COUPLINGCONSUMPTIONREPORT, PIN135W1PIECEWITHERROR PIECEWITHERROR, PIN135W1STANDARERROREA STANDARERROREA, object userState)
        {
            if ((this.PIN135W1OperationCompleted == null))
            {
                this.PIN135W1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnPIN135W1OperationCompleted);
            }
            this.InvokeAsync("PIN135W1", new object[] {
                        COUPLINGCONSUMPTIONREPORT,
                        PIECEWITHERROR,
                        STANDARERROREA}, this.PIN135W1OperationCompleted, userState);
        }

        private void OnPIN135W1OperationCompleted(object arg)
        {
            if ((this.PIN135W1Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PIN135W1Completed(this, new PIN135W1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PIN149F", RequestNamespace = "urn:com-softwareag-entirex-rpc:MANUGPV", ResponseNamespace = "urn:com-softwareag-entirex-rpc:MANUGPV", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DETAILEDTRANSACTIONSTATUS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FResponseDETAILEDTRANSACTIONSTATUS PIN149F([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] PIN149FFINISHINGREPORT FINISHINGREPORT, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] PIN149FDETAILEDTRANSACTIONSTATUS DETAILEDTRANSACTIONSTATUS, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string SECURITYID, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary")] byte[] LANGUAGEID, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string ERRORTYPE, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] ref decimal ERRORNUMBER, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string ERRORDESCRIPTION)
        {
            object[] results = this.Invoke("PIN149F", new object[] {
                        FINISHINGREPORT,
                        DETAILEDTRANSACTIONSTATUS,
                        SECURITYID,
                        LANGUAGEID,
                        ERRORTYPE,
                        ERRORNUMBER,
                        ERRORDESCRIPTION});
            ERRORTYPE = ((string)(results[1]));
            ERRORNUMBER = ((decimal)(results[2]));
            ERRORDESCRIPTION = ((string)(results[3]));
            return ((PIN149FResponseDETAILEDTRANSACTIONSTATUS)(results[0]));
        }

        /// <remarks/>
        public void PIN149FAsync(PIN149FFINISHINGREPORT FINISHINGREPORT, PIN149FDETAILEDTRANSACTIONSTATUS DETAILEDTRANSACTIONSTATUS, string SECURITYID, byte[] LANGUAGEID, string ERRORTYPE, decimal ERRORNUMBER, string ERRORDESCRIPTION)
        {
            this.PIN149FAsync(FINISHINGREPORT, DETAILEDTRANSACTIONSTATUS, SECURITYID, LANGUAGEID, ERRORTYPE, ERRORNUMBER, ERRORDESCRIPTION, null);
        }

        /// <remarks/>
        public void PIN149FAsync(PIN149FFINISHINGREPORT FINISHINGREPORT, PIN149FDETAILEDTRANSACTIONSTATUS DETAILEDTRANSACTIONSTATUS, string SECURITYID, byte[] LANGUAGEID, string ERRORTYPE, decimal ERRORNUMBER, string ERRORDESCRIPTION, object userState)
        {
            if ((this.PIN149FOperationCompleted == null))
            {
                this.PIN149FOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPIN149FOperationCompleted);
            }
            this.InvokeAsync("PIN149F", new object[] {
                        FINISHINGREPORT,
                        DETAILEDTRANSACTIONSTATUS,
                        SECURITYID,
                        LANGUAGEID,
                        ERRORTYPE,
                        ERRORNUMBER,
                        ERRORDESCRIPTION}, this.PIN149FOperationCompleted, userState);
        }

        private void OnPIN149FOperationCompleted(object arg)
        {
            if ((this.PIN149FCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PIN149FCompleted(this, new PIN149FCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1COUPLINGCONSUMPTIONREPORT
    {

        private PIN135W1COUPLINGCONSUMPTIONREPORTGENERALINFORMATION gENERALINFORMATIONField;

        private PIN135W1COUPLINGCONSUMPTIONREPORTCONSUMPTIONREPORT cONSUMPTIONREPORTField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN135W1COUPLINGCONSUMPTIONREPORTGENERALINFORMATION GENERALINFORMATION
        {
            get
            {
                return this.gENERALINFORMATIONField;
            }
            set
            {
                this.gENERALINFORMATIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN135W1COUPLINGCONSUMPTIONREPORTCONSUMPTIONREPORT CONSUMPTIONREPORT
        {
            get
            {
                return this.cONSUMPTIONREPORTField;
            }
            set
            {
                this.cONSUMPTIONREPORTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1COUPLINGCONSUMPTIONREPORTGENERALINFORMATION
    {

        private string tRANSACTIONNUMBERField;

        private string mACHINEField;

        private string dATEField;

        private string sHIFTField;

        private string pIPESHANDLINGMATERIALField;

        private string cOUPLINGHANDLINGMATERIALField;

        private string pIPESPRODUCTIONORDERField;

        private string cOUPLINGLOTField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSACTIONNUMBER
        {
            get
            {
                return this.tRANSACTIONNUMBERField;
            }
            set
            {
                this.tRANSACTIONNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MACHINE
        {
            get
            {
                return this.mACHINEField;
            }
            set
            {
                this.mACHINEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHIFT
        {
            get
            {
                return this.sHIFTField;
            }
            set
            {
                this.sHIFTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIPESHANDLINGMATERIAL
        {
            get
            {
                return this.pIPESHANDLINGMATERIALField;
            }
            set
            {
                this.pIPESHANDLINGMATERIALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUPLINGHANDLINGMATERIAL
        {
            get
            {
                return this.cOUPLINGHANDLINGMATERIALField;
            }
            set
            {
                this.cOUPLINGHANDLINGMATERIALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIPESPRODUCTIONORDER
        {
            get
            {
                return this.pIPESPRODUCTIONORDERField;
            }
            set
            {
                this.pIPESPRODUCTIONORDERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUPLINGLOT
        {
            get
            {
                return this.cOUPLINGLOTField;
            }
            set
            {
                this.cOUPLINGLOTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1COUPLINGCONSUMPTIONREPORTCONSUMPTIONREPORT
    {

        private string[] pIPEHEATNUMBERField;

        private decimal[] pIPENUMBERField;

        private string[] cOUPLINGPRODUCTIONORDERField;

        private string[] cOUPLINGHEATNUMBERField;

        private decimal[] hOLLOWNUMBERField;

        private string[] fINISHEDCOUPLINGNUMBERField;

        private string[] cONSUMPTIONMARKField;

        private string[] uSERIDField;

        private string[] hOURField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] PIPEHEATNUMBER
        {
            get
            {
                return this.pIPEHEATNUMBERField;
            }
            set
            {
                this.pIPEHEATNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public decimal[] PIPENUMBER
        {
            get
            {
                return this.pIPENUMBERField;
            }
            set
            {
                this.pIPENUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] COUPLINGPRODUCTIONORDER
        {
            get
            {
                return this.cOUPLINGPRODUCTIONORDERField;
            }
            set
            {
                this.cOUPLINGPRODUCTIONORDERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] COUPLINGHEATNUMBER
        {
            get
            {
                return this.cOUPLINGHEATNUMBERField;
            }
            set
            {
                this.cOUPLINGHEATNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public decimal[] HOLLOWNUMBER
        {
            get
            {
                return this.hOLLOWNUMBERField;
            }
            set
            {
                this.hOLLOWNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] FINISHEDCOUPLINGNUMBER
        {
            get
            {
                return this.fINISHEDCOUPLINGNUMBERField;
            }
            set
            {
                this.fINISHEDCOUPLINGNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] CONSUMPTIONMARK
        {
            get
            {
                return this.cONSUMPTIONMARKField;
            }
            set
            {
                this.cONSUMPTIONMARKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] USERID
        {
            get
            {
                return this.uSERIDField;
            }
            set
            {
                this.uSERIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] HOUR
        {
            get
            {
                return this.hOURField;
            }
            set
            {
                this.hOURField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1PIECEWITHERROR
    {

        private decimal eRRORPIPENUMBERField;

        private string eRRORCOUPLINGNUMBERField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORPIPENUMBER
        {
            get
            {
                return this.eRRORPIPENUMBERField;
            }
            set
            {
                this.eRRORPIPENUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRORCOUPLINGNUMBER
        {
            get
            {
                return this.eRRORCOUPLINGNUMBERField;
            }
            set
            {
                this.eRRORCOUPLINGNUMBERField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1STANDARERROREA
    {

        private string sECURITYIDField;

        private decimal lANGUAGEIDField;

        private string eRRORTYPEField;

        private decimal eRRORNUMBERField;

        private string eRRORDESCRIPTIONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SECURITYID
        {
            get
            {
                return this.sECURITYIDField;
            }
            set
            {
                this.sECURITYIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LANGUAGEID
        {
            get
            {
                return this.lANGUAGEIDField;
            }
            set
            {
                this.lANGUAGEIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRORTYPE
        {
            get
            {
                return this.eRRORTYPEField;
            }
            set
            {
                this.eRRORTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORNUMBER
        {
            get
            {
                return this.eRRORNUMBERField;
            }
            set
            {
                this.eRRORNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRORDESCRIPTION
        {
            get
            {
                return this.eRRORDESCRIPTIONField;
            }
            set
            {
                this.eRRORDESCRIPTIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1ResponseCOUPLINGCONSUMPTIONREPORT
    {

        private PIN135W1ResponseCOUPLINGCONSUMPTIONREPORTGENERALINFORMATION gENERALINFORMATIONField;

        private PIN135W1ResponseCOUPLINGCONSUMPTIONREPORTCONSUMPTIONREPORT cONSUMPTIONREPORTField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN135W1ResponseCOUPLINGCONSUMPTIONREPORTGENERALINFORMATION GENERALINFORMATION
        {
            get
            {
                return this.gENERALINFORMATIONField;
            }
            set
            {
                this.gENERALINFORMATIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN135W1ResponseCOUPLINGCONSUMPTIONREPORTCONSUMPTIONREPORT CONSUMPTIONREPORT
        {
            get
            {
                return this.cONSUMPTIONREPORTField;
            }
            set
            {
                this.cONSUMPTIONREPORTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1ResponseCOUPLINGCONSUMPTIONREPORTGENERALINFORMATION
    {

        private string tRANSACTIONNUMBERField;

        private string mACHINEField;

        private string dATEField;

        private string sHIFTField;

        private string pIPESHANDLINGMATERIALField;

        private string cOUPLINGHANDLINGMATERIALField;

        private string pIPESPRODUCTIONORDERField;

        private string cOUPLINGLOTField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSACTIONNUMBER
        {
            get
            {
                return this.tRANSACTIONNUMBERField;
            }
            set
            {
                this.tRANSACTIONNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MACHINE
        {
            get
            {
                return this.mACHINEField;
            }
            set
            {
                this.mACHINEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHIFT
        {
            get
            {
                return this.sHIFTField;
            }
            set
            {
                this.sHIFTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIPESHANDLINGMATERIAL
        {
            get
            {
                return this.pIPESHANDLINGMATERIALField;
            }
            set
            {
                this.pIPESHANDLINGMATERIALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUPLINGHANDLINGMATERIAL
        {
            get
            {
                return this.cOUPLINGHANDLINGMATERIALField;
            }
            set
            {
                this.cOUPLINGHANDLINGMATERIALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIPESPRODUCTIONORDER
        {
            get
            {
                return this.pIPESPRODUCTIONORDERField;
            }
            set
            {
                this.pIPESPRODUCTIONORDERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUPLINGLOT
        {
            get
            {
                return this.cOUPLINGLOTField;
            }
            set
            {
                this.cOUPLINGLOTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1ResponseCOUPLINGCONSUMPTIONREPORTCONSUMPTIONREPORT
    {

        private string[] pIPEHEATNUMBERField;

        private decimal[] pIPENUMBERField;

        private string[] cOUPLINGPRODUCTIONORDERField;

        private string[] cOUPLINGHEATNUMBERField;

        private decimal[] hOLLOWNUMBERField;

        private string[] fINISHEDCOUPLINGNUMBERField;

        private string[] cONSUMPTIONMARKField;

        private string[] uSERIDField;

        private string[] hOURField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] PIPEHEATNUMBER
        {
            get
            {
                return this.pIPEHEATNUMBERField;
            }
            set
            {
                this.pIPEHEATNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public decimal[] PIPENUMBER
        {
            get
            {
                return this.pIPENUMBERField;
            }
            set
            {
                this.pIPENUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] COUPLINGPRODUCTIONORDER
        {
            get
            {
                return this.cOUPLINGPRODUCTIONORDERField;
            }
            set
            {
                this.cOUPLINGPRODUCTIONORDERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] COUPLINGHEATNUMBER
        {
            get
            {
                return this.cOUPLINGHEATNUMBERField;
            }
            set
            {
                this.cOUPLINGHEATNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public decimal[] HOLLOWNUMBER
        {
            get
            {
                return this.hOLLOWNUMBERField;
            }
            set
            {
                this.hOLLOWNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] FINISHEDCOUPLINGNUMBER
        {
            get
            {
                return this.fINISHEDCOUPLINGNUMBERField;
            }
            set
            {
                this.fINISHEDCOUPLINGNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] CONSUMPTIONMARK
        {
            get
            {
                return this.cONSUMPTIONMARKField;
            }
            set
            {
                this.cONSUMPTIONMARKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] USERID
        {
            get
            {
                return this.uSERIDField;
            }
            set
            {
                this.uSERIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] HOUR
        {
            get
            {
                return this.hOURField;
            }
            set
            {
                this.hOURField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1ResponsePIECEWITHERROR
    {

        private decimal eRRORPIPENUMBERField;

        private string eRRORCOUPLINGNUMBERField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORPIPENUMBER
        {
            get
            {
                return this.eRRORPIPENUMBERField;
            }
            set
            {
                this.eRRORPIPENUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRORCOUPLINGNUMBER
        {
            get
            {
                return this.eRRORCOUPLINGNUMBERField;
            }
            set
            {
                this.eRRORCOUPLINGNUMBERField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN135W1ResponseSTANDARERROREA
    {

        private string sECURITYIDField;

        private decimal lANGUAGEIDField;

        private string eRRORTYPEField;

        private decimal eRRORNUMBERField;

        private string eRRORDESCRIPTIONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SECURITYID
        {
            get
            {
                return this.sECURITYIDField;
            }
            set
            {
                this.sECURITYIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LANGUAGEID
        {
            get
            {
                return this.lANGUAGEIDField;
            }
            set
            {
                this.lANGUAGEIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRORTYPE
        {
            get
            {
                return this.eRRORTYPEField;
            }
            set
            {
                this.eRRORTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORNUMBER
        {
            get
            {
                return this.eRRORNUMBERField;
            }
            set
            {
                this.eRRORNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRORDESCRIPTION
        {
            get
            {
                return this.eRRORDESCRIPTIONField;
            }
            set
            {
                this.eRRORDESCRIPTIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FFINISHINGREPORT
    {

        private PIN149FFINISHINGREPORTGENERALINFORMATION gENERALINFORMATIONField;

        private PIN149FFINISHINGREPORTPIPESPRODUCTION pIPESPRODUCTIONField;

        private PIN149FFINISHINGREPORTMACHINESPRODUCTION mACHINESPRODUCTIONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FFINISHINGREPORTGENERALINFORMATION GENERALINFORMATION
        {
            get
            {
                return this.gENERALINFORMATIONField;
            }
            set
            {
                this.gENERALINFORMATIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FFINISHINGREPORTPIPESPRODUCTION PIPESPRODUCTION
        {
            get
            {
                return this.pIPESPRODUCTIONField;
            }
            set
            {
                this.pIPESPRODUCTIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FFINISHINGREPORTMACHINESPRODUCTION MACHINESPRODUCTION
        {
            get
            {
                return this.mACHINESPRODUCTIONField;
            }
            set
            {
                this.mACHINESPRODUCTIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FFINISHINGREPORTGENERALINFORMATION
    {

        private string tRANSACTIONNUMBERField;

        private string hANDLINGTYPEField;

        private string sTOCKTYPEField;

        private string rEPORTTYPEField;

        private string pRODUCTIONORDERField;

        private string hEATNUMBERField;

        private string fACTORYLOTField;

        private string lOCATIONField;

        private string mANUFACTURINGSTATUSINField;

        private string mANUFACTURINGSTATUSOUTField;

        private decimal tOTALPIECESField;

        private string pRINTTAGField;

        private string pRINTERField;

        private string cOMMENTSField;

        private string gENERATEDETAILField;

        private string rENUMBERPIPESField;

        private string nEXTMACHINEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSACTIONNUMBER
        {
            get
            {
                return this.tRANSACTIONNUMBERField;
            }
            set
            {
                this.tRANSACTIONNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HANDLINGTYPE
        {
            get
            {
                return this.hANDLINGTYPEField;
            }
            set
            {
                this.hANDLINGTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOCKTYPE
        {
            get
            {
                return this.sTOCKTYPEField;
            }
            set
            {
                this.sTOCKTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REPORTTYPE
        {
            get
            {
                return this.rEPORTTYPEField;
            }
            set
            {
                this.rEPORTTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTIONORDER
        {
            get
            {
                return this.pRODUCTIONORDERField;
            }
            set
            {
                this.pRODUCTIONORDERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HEATNUMBER
        {
            get
            {
                return this.hEATNUMBERField;
            }
            set
            {
                this.hEATNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FACTORYLOT
        {
            get
            {
                return this.fACTORYLOTField;
            }
            set
            {
                this.fACTORYLOTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOCATION
        {
            get
            {
                return this.lOCATIONField;
            }
            set
            {
                this.lOCATIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANUFACTURINGSTATUSIN
        {
            get
            {
                return this.mANUFACTURINGSTATUSINField;
            }
            set
            {
                this.mANUFACTURINGSTATUSINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANUFACTURINGSTATUSOUT
        {
            get
            {
                return this.mANUFACTURINGSTATUSOUTField;
            }
            set
            {
                this.mANUFACTURINGSTATUSOUTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TOTALPIECES
        {
            get
            {
                return this.tOTALPIECESField;
            }
            set
            {
                this.tOTALPIECESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRINTTAG
        {
            get
            {
                return this.pRINTTAGField;
            }
            set
            {
                this.pRINTTAGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRINTER
        {
            get
            {
                return this.pRINTERField;
            }
            set
            {
                this.pRINTERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENTS
        {
            get
            {
                return this.cOMMENTSField;
            }
            set
            {
                this.cOMMENTSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GENERATEDETAIL
        {
            get
            {
                return this.gENERATEDETAILField;
            }
            set
            {
                this.gENERATEDETAILField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RENUMBERPIPES
        {
            get
            {
                return this.rENUMBERPIPESField;
            }
            set
            {
                this.rENUMBERPIPESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NEXTMACHINE
        {
            get
            {
                return this.nEXTMACHINEField;
            }
            set
            {
                this.nEXTMACHINEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FFINISHINGREPORTPIPESPRODUCTION
    {

        private string[] pIPENUMBERField;

        private string[] fACTORYIDOUTField;

        private decimal[] rEPROCESSINGNUMBERField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] PIPENUMBER
        {
            get
            {
                return this.pIPENUMBERField;
            }
            set
            {
                this.pIPENUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] FACTORYIDOUT
        {
            get
            {
                return this.fACTORYIDOUTField;
            }
            set
            {
                this.fACTORYIDOUTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public decimal[] REPROCESSINGNUMBER
        {
            get
            {
                return this.rEPROCESSINGNUMBERField;
            }
            set
            {
                this.rEPROCESSINGNUMBERField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FFINISHINGREPORTMACHINESPRODUCTION
    {

        private string[] mACHINEField;

        private string[][] pROCCESEDSIDEField;

        private string[][] dATEField;

        private string[][] hOURField;

        private string[][] uSERIDField;

        private string[][] pRODUCTIONTYPEField;

        private string[][] rEJECTIONCAUSEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] MACHINE
        {
            get
            {
                return this.mACHINEField;
            }
            set
            {
                this.mACHINEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("string_1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false, NestingLevel = 1)]
        public string[][] PROCCESEDSIDE
        {
            get
            {
                return this.pROCCESEDSIDEField;
            }
            set
            {
                this.pROCCESEDSIDEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("string_1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false, NestingLevel = 1)]
        public string[][] DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("string_1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false, NestingLevel = 1)]
        public string[][] HOUR
        {
            get
            {
                return this.hOURField;
            }
            set
            {
                this.hOURField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("string_1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false, NestingLevel = 1)]
        public string[][] USERID
        {
            get
            {
                return this.uSERIDField;
            }
            set
            {
                this.uSERIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("string_1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false, NestingLevel = 1)]
        public string[][] PRODUCTIONTYPE
        {
            get
            {
                return this.pRODUCTIONTYPEField;
            }
            set
            {
                this.pRODUCTIONTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("string_1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false, NestingLevel = 1)]
        public string[][] REJECTIONCAUSE
        {
            get
            {
                return this.rEJECTIONCAUSEField;
            }
            set
            {
                this.rEJECTIONCAUSEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FDETAILEDTRANSACTIONSTATUS
    {

        private PIN149FDETAILEDTRANSACTIONSTATUSDESCRIPTIVEERROR dESCRIPTIVEERRORField;

        private PIN149FDETAILEDTRANSACTIONSTATUSREPORTEDPIPES rEPORTEDPIPESField;

        private PIN149FDETAILEDTRANSACTIONSTATUSBUNDLEANDTRANSACTIONSCREATED bUNDLEANDTRANSACTIONSCREATEDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FDETAILEDTRANSACTIONSTATUSDESCRIPTIVEERROR DESCRIPTIVEERROR
        {
            get
            {
                return this.dESCRIPTIVEERRORField;
            }
            set
            {
                this.dESCRIPTIVEERRORField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FDETAILEDTRANSACTIONSTATUSREPORTEDPIPES REPORTEDPIPES
        {
            get
            {
                return this.rEPORTEDPIPESField;
            }
            set
            {
                this.rEPORTEDPIPESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FDETAILEDTRANSACTIONSTATUSBUNDLEANDTRANSACTIONSCREATED BUNDLEANDTRANSACTIONSCREATED
        {
            get
            {
                return this.bUNDLEANDTRANSACTIONSCREATEDField;
            }
            set
            {
                this.bUNDLEANDTRANSACTIONSCREATEDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FDETAILEDTRANSACTIONSTATUSDESCRIPTIVEERROR
    {

        private decimal[] dETAILEDERRORNUMBERField;

        private string[] dETAILEDERRORDESCRIPTIONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public decimal[] DETAILEDERRORNUMBER
        {
            get
            {
                return this.dETAILEDERRORNUMBERField;
            }
            set
            {
                this.dETAILEDERRORNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] DETAILEDERRORDESCRIPTION
        {
            get
            {
                return this.dETAILEDERRORDESCRIPTIONField;
            }
            set
            {
                this.dETAILEDERRORDESCRIPTIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FDETAILEDTRANSACTIONSTATUSREPORTEDPIPES
    {

        private string[] dETAILEDPIPENUMBERField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] DETAILEDPIPENUMBER
        {
            get
            {
                return this.dETAILEDPIPENUMBERField;
            }
            set
            {
                this.dETAILEDPIPENUMBERField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FDETAILEDTRANSACTIONSTATUSBUNDLEANDTRANSACTIONSCREATED
    {

        private string pIPTRANSACTIONField;

        private decimal bUNDLECREATEDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIPTRANSACTION
        {
            get
            {
                return this.pIPTRANSACTIONField;
            }
            set
            {
                this.pIPTRANSACTIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUNDLECREATED
        {
            get
            {
                return this.bUNDLECREATEDField;
            }
            set
            {
                this.bUNDLECREATEDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FResponseDETAILEDTRANSACTIONSTATUS
    {

        private PIN149FResponseDETAILEDTRANSACTIONSTATUSDESCRIPTIVEERROR dESCRIPTIVEERRORField;

        private PIN149FResponseDETAILEDTRANSACTIONSTATUSREPORTEDPIPES rEPORTEDPIPESField;

        private PIN149FResponseDETAILEDTRANSACTIONSTATUSBUNDLEANDTRANSACTIONSCREATED bUNDLEANDTRANSACTIONSCREATEDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FResponseDETAILEDTRANSACTIONSTATUSDESCRIPTIVEERROR DESCRIPTIVEERROR
        {
            get
            {
                return this.dESCRIPTIVEERRORField;
            }
            set
            {
                this.dESCRIPTIVEERRORField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FResponseDETAILEDTRANSACTIONSTATUSREPORTEDPIPES REPORTEDPIPES
        {
            get
            {
                return this.rEPORTEDPIPESField;
            }
            set
            {
                this.rEPORTEDPIPESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PIN149FResponseDETAILEDTRANSACTIONSTATUSBUNDLEANDTRANSACTIONSCREATED BUNDLEANDTRANSACTIONSCREATED
        {
            get
            {
                return this.bUNDLEANDTRANSACTIONSCREATEDField;
            }
            set
            {
                this.bUNDLEANDTRANSACTIONSCREATEDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FResponseDETAILEDTRANSACTIONSTATUSDESCRIPTIVEERROR
    {

        private decimal[] dETAILEDERRORNUMBERField;

        private string[] dETAILEDERRORDESCRIPTIONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public decimal[] DETAILEDERRORNUMBER
        {
            get
            {
                return this.dETAILEDERRORNUMBERField;
            }
            set
            {
                this.dETAILEDERRORNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] DETAILEDERRORDESCRIPTION
        {
            get
            {
                return this.dETAILEDERRORDESCRIPTIONField;
            }
            set
            {
                this.dETAILEDERRORDESCRIPTIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FResponseDETAILEDTRANSACTIONSTATUSREPORTEDPIPES
    {

        private string[] dETAILEDPIPENUMBERField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] DETAILEDPIPENUMBER
        {
            get
            {
                return this.dETAILEDPIPENUMBERField;
            }
            set
            {
                this.dETAILEDPIPENUMBERField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:com-softwareag-entirex-rpc:MANUGPV")]
    public partial class PIN149FResponseDETAILEDTRANSACTIONSTATUSBUNDLEANDTRANSACTIONSCREATED
    {

        private string pIPTRANSACTIONField;

        private decimal bUNDLECREATEDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIPTRANSACTION
        {
            get
            {
                return this.pIPTRANSACTIONField;
            }
            set
            {
                this.pIPTRANSACTIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUNDLECREATED
        {
            get
            {
                return this.bUNDLECREATEDField;
            }
            set
            {
                this.bUNDLECREATEDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PIN135W1CompletedEventHandler(object sender, PIN135W1CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PIN135W1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal PIN135W1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public PIN135W1ResponseCOUPLINGCONSUMPTIONREPORT Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PIN135W1ResponseCOUPLINGCONSUMPTIONREPORT)(this.results[0]));
            }
        }

        /// <remarks/>
        public PIN135W1ResponsePIECEWITHERROR PIECEWITHERROR1
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PIN135W1ResponsePIECEWITHERROR)(this.results[1]));
            }
        }

        /// <remarks/>
        public PIN135W1ResponseSTANDARERROREA STANDARERROREA1
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PIN135W1ResponseSTANDARERROREA)(this.results[2]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PIN149FCompletedEventHandler(object sender, PIN149FCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PIN149FCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal PIN149FCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public PIN149FResponseDETAILEDTRANSACTIONSTATUS Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PIN149FResponseDETAILEDTRANSACTIONSTATUS)(this.results[0]));
            }
        }

        /// <remarks/>
        public string ERRORTYPE
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }

        /// <remarks/>
        public decimal ERRORNUMBER
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[2]));
            }
        }

        /// <remarks/>
        public string ERRORDESCRIPTION
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
}

#pragma warning restore 1591